### ISSUE TITLE
Problem to access table from GAMA

### ISSUE THREAD

**Issue by agrignard** [yasushisakai/CityIOServer#132]
Hi @yasushisakai I am not sure if this is the right place to right this issue. I am trying to access to a(any) table from GAMA using GamaBrix (https://github.com/CityScope/CS_GAMABrix/issues/8). It used to work pretty well, however I have the felling something is wrong somewhere (I cannot also see or edit  project on CityScopeJS) 

If it can help this the message I have from GAMA when trying to access this table ```cityscopejs_gama```

`````
 at cycle 0: Java error: RuntimeException
in create brix from: geogrid with: [name::nil];
RuntimeException: Unexpected token END OF FILE at position 65369.
org.geotools.geojson.feature.FeatureJSON$FeatureCollectionIterator.readNext(FeatureJSON.java:718)
org.geotools.geojson.feature.FeatureJSON$FeatureCollectionIterator.hasNext(FeatureJSON.java:703)
org.geotools.geojson.feature.FeatureJSON.readFeatureCollection(FeatureJSON.java:357)
msi.gama.util.file.GamaGeoJsonFile.getFeatureCollection(GamaGeoJsonFile.java:132)
msi.gama.util.file.GamaGisFile.readShapes(GamaGisFile.java:157)
msi.gama.util.file.GamaGeoJsonFile.fillBuffer(GamaGeoJsonFile.java:107)
msi.gama.util.file.GamaFile.getContents(GamaFile.java:341)
`````

Let me know if it's the right place to right this issue

**Comment by yasushisakai** [comment]
I most certainly think that it's because of the server reaching its storage limit.
I'm looking into ways how I can mitigate this.

We are backing up every unique data now, so if clients send random data this will all be written in history.

**Comment by agrignard** [comment]
@yasushisakai am I missing something in the way to access a table? I described the issue here
https://github.com/CityScope/CS_GAMABrix/issues/9

I can access it but he content seems to be not sync with the current table

**Comment by agrignard** [comment]
This issue was due to the server being full.

**Comment by agrignard** [comment]
Solution found by @ptaillandier here https://github.com/gama-platform/gama/issues/3249
