### ISSUE TITLE
Local server

### ISSUE THREAD

**Issue by vbaryshev** [yasushisakai/CityIOServer#133]
Hello, now do I need to get credentials to deploy a local server? 
RUN chown -R $APP_USER:$APP_USER ${APP}

Thanks!

**Comment by yasushisakai** [comment]
Hi, no you don't need any of the credentials to run a cityio instance.
It just assumes that you have a redis instance running in the default. (This can be a docker image too)

https://cityscope.media.mit.edu/backend/Build

**Comment by vbaryshev** [comment]
Thanks!

**Comment by vbaryshev** [comment]
Hello, can you clarify the correct path to the API table when starting the local cityIO server from docker?
1. redis-server run
![Снимок экрана от 2022-01-08 18-28-06](https://user-images.githubusercontent.com/7428565/148733280-9ccf3d96-521e-468c-bef5-9b6783d0a9e6.png)

2. docker city IO, port 8040
![Снимок экрана от 2022-01-08 20-11-01](https://user-images.githubusercontent.com/7428565/148733310-fb741346-f0aa-4596-9b43-c1ce64a3f390.png)

3. I changed the settings here, but I may have made a mistake in the path to the API table ~ /src/settings/settings.json. ?
![Снимок экрана от 2022-01-10 10-27-32](https://user-images.githubusercontent.com/7428565/148733340-754c214b-3321-44ed-a7f0-d69cfccf1570.png)

Thanks!
